# Generated by Django 5.2.1 on 2025-05-24 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_mappings', to='companies.company')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_mappings', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Farmer-Company Mapping',
                'verbose_name_plural': 'Farmer-Company Mappings',
                'db_table': 'farmer_mappings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farmer'], name='farmer_mapp_farmer__f67f51_idx'), models.Index(fields=['company'], name='farmer_mapp_company_fcfdb8_idx'), models.Index(fields=['status'], name='farmer_mapp_status_a48353_idx')],
                'unique_together': {('farmer', 'company')},
            },
        ),
    ]
